services:
  - type: web
    name: saas-sales-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: HUGGINGFACE_API_TOKEN
        sync: false 